
; ***********************************************************************
; DASETUP.INI
; This is the .ini file for dasetup.exe for MDAC 2.8 32 bit setup
; ***********************************************************************

; ValidOS values
;  these can be OR'd together..
; Win95 = 1
; Win98 = 2
; NT4 = 4
; W2K = 8
; Millennium = 16
; WXP = 32
; W2K3 = 64
; All = 4294967295 (0xFFFFFFFF)

; General (Global) settings
[General]
ProductName=Microsoft Data Access Components 2.8 SP1
ProductBuild=2.81.1117.6
ProductUrl=http://www.microsoft.com/data
ProductVersionKey=SOFTWARE\Microsoft\DataAccess
ProductVersionValue=FullInstallVer
InstanceName=MDAC
CheckInUseFiles=1
EULAFile=MDACEULA.RTF
EULAType=rtf
;BackupSize=10
;InstallSize=20
SupportsTS=1
SupportsMUI=0
CheckForDiskSpace=1
ValidOs=31


; List of packages in order to be installed
[Packages]
A=MDAC_SAFER
B=SETUP_LIBS
C=C_RUNTIME_LIBS
D=MTX_FILES
E=SETUP_RSP_DOWNLEVEL
F=SETUP_RSP_FILES
G=DASETUP_DOWNLEVEL
H=DASETUP_FILES
I=WDSETUP_DOWNLEVEL
J=WDSETUP_MILLENNIUM
K=WDSETUP_W2K_MIGRATION
L=MDAC_DOWNLEVEL
M=MDAC_MILLENNIUM
N=MDAC_W2K_MIGRATION
O=MSXML_XPAK
P=MSXML_FILES
Q=SQLXMLX_XPAK
R=SQLXMLX
T=SQLNET_DOWNLEVEL
V=SQLNET_MILLENNIUM
W=SQLNET_W2K_MIGRATION
X=SQLODBC_DOWNLEVEL
Y=SQLODBC_MILLENNIUM
Z=SQLODBC_W2K_MIGRATION
AA=SQLOLEDB_DOWNLEVEL
AB=SQLOLEDB_MILLENNIUM
AC=SQLOLEDB_W2K_MIGRATION
AD=JET_FILES
AE=NEW_MUI_ENGINE
AF=REG_MDAC_VERSION
AG=BID_INTERFACE
AH=BID_W2K
AI=FINISH

[MDAC_SAFER]
Name=Microsoft Data Access Components
ComponentName=BIDINTERFACE
Catalog=
Dependencies=
InstallType=inf
CabFile=
InfFile=mdacsafe.inf
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall
PostInstallCmd=
ExtractCab=0
UseRollback=0
RebootAfter=0
ValidOs=32

[SETUP_LIBS]
Name=Microsoft Setup Libraries
ComponentName=SETUP_LIBS
Catalog=
Dependencies=
InstallType=inf
CabFile=setupapi.cab
InfFile=setupapi.inf
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall
ExtractCab=1
UseRollback=0
RebootAfter=0
ValidOs=3


[C_RUNTIME_LIBS]
Name=Microsoft C/C++ Runtime Libraries
ComponentName=C_RUNTIME_LIBS
Catalog=
Dependencies=
InstallType=inf
CabFile=msvcrt.cab
InfFile=msvcrt.inf
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall.NT
ExtractCab=0
UseRollback=0
RebootAfter=0
ValidOs=7


[MTX_FILES]
Name=MTX System Files
ComponentName=MTX_FILES
Catalog=
Dependencies=
InstallType=inf
CabFile=mtxfiles.cab
InfFile=mtxfiles.inf
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall.NT
ExtractCab=0
UseRollback=0
RebootAfter=0
ValidOs=7


[DASETUP_DOWNLEVEL]
Name=MDAC Setup Files
ComponentName=DASETUP27
Catalog=
Dependencies=
InstallType=inf
CabFile=dasetup.cab
InfFile=dasetupd.inf
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall.NT
ExtractCab=0
UseRollback=0
RebootAfter=0
ValidOs=23


[DASETUP_FILES]
Name=MDAC Setup Files
ComponentName=DASETUP28SP1
Catalog=dasetup.cat
Dependencies=
InstallType=xpak
CabFile=dasetup.cab
InfFile=dasetup.inf
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall
ExtractCab=0
UseRollback=0
RebootAfter=0
ValidOs=31
CheckXPakVer=1



[SETUP_RSP_DOWNLEVEL]
Name=MDAC Setup Response Files
ComponentName=SETUP_RSP_FILES27
Catalog=
Dependencies=
InstallType=inf
CabFile=rspfiles.cab
InfFile=rspfiled.inf
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall.NT
ExtractCab=0
UseRollback=0
RebootAfter=0
ValidOs=23


[SETUP_RSP_FILES]
Name=MDAC Setup Response Files
ComponentName=SETUP_RSP_FILES28SP1
Catalog=rspfiles.cat
Dependencies=
InstallType=xpak
CabFile=rspfiles.cab
InfFile=rspfiles.inf
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall
ExtractCab=0
UseRollback=0
RebootAfter=0
ValidOs=31
CheckXPakVer=1


[WDSETUP_DOWNLEVEL]
Name=WebData Setup Files
ComponentName=WDSETUP28SP1
Catalog=
Dependencies=
InstallType=inf
CabFile=WDSETUP.CAB
InfFile=WDSET_DL.INF
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall.NT
ExtractCab=0
UseRollback=0
RebootAfter=0
ValidOs=7


[WDSETUP_MILLENNIUM]
Name=WebData Setup Files
ComponentName=WDSETUP28SP1
Catalog=
Dependencies=
InstallType=inf
CabFile=WDSETUP.CAB
InfFile=WDSETUPM.INF
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall
ExtractCab=0
UseRollback=0
RebootAfter=0
ValidOs=16


[WDSETUP_W2K_MIGRATION]
Name=WebData Setup Files
ComponentName=WDSETUP28SP1
Catalog=WDSETUP.CAT
Dependencies=
InstallType=xpak
CabFile=WDSETUP.CAB
InfFile=WDSETUP.INF
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall
ExtractCab=0
UseRollback=0
RebootAfter=0
ValidOs=31
CheckXPakVer=1



[MDAC_DOWNLEVEL]
Name=Microsoft Data Access Components
ComponentName=MDAC_CORE28SP1
Catalog=
Dependencies=C_RUNTIME_LIBS,MTX_FILES,WDSETUP28SP1
InstallType=inf
CabFile=MDACXPAK.CAB
InfFile=MDACXPDL.INF
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall.NT
PostInstallCmd=%11%\odbcconf.exe /S /Lv %25%\dasetup.log /F %11%\mdaccore.rsp
ExtractCab=0
UseRollback=1
RebootAfter=0
ValidOs=7


[MDAC_MILLENNIUM]
Name=Microsoft Data Access Components
ComponentName=MDAC_CORE28SP1
Catalog=
Dependencies=C_RUNTIME_LIBS,MTX_FILES,WDSETUP28SP1
InstallType=inf
CabFile=MDACXPAK.CAB
InfFile=MDACXPKM.INF
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall
PostInstallCmd=%11%\odbcconf.exe /S /Lv %25%\dasetup.log /F %11%\mdaccore.rsp
ExtractCab=0
UseRollback=1
RebootAfter=0
ValidOs=16


[MDAC_W2K_MIGRATION]
Name=Microsoft Data Access Components
ComponentName=MDAC_CORE28SP1
Catalog=MDACXPAK.CAT
Dependencies=C_RUNTIME_LIBS,MTX_FILES,WDSETUP28SP1
InstallType=xpak
CABFile=MDACXPAK.CAB
InfFile=MDACXPAK.INF
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall
PostInstallCmd=%11%\odbcconf.exe /S /Lv %25%\dasetup.log /F %11%\mdaccore.rsp
ExtractCab=0
UseRollback=1
RebootAfter=0
ValidOS=31
CheckXPakVer=1







[MSXML_FILES]
Name=Microsoft XML Parser
ComponentName=MSXML_MDAC28SP1
Catalog=
Dependencies=
InstallType=inf
CabFile=MSXMLX.cab
InfFile=MSXML.inf
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall.NT
ExtractCab=0
UseRollback=1
RebootAfter=0
ValidOs=23


[MSXML_XPAK]
Name=Microsoft XML Parser
ComponentName=MSXML_MDAC28SP1
Catalog=MSXMLX.CAT
Dependencies=
InstallType=xpak
CabFile=MSXMLX.cab
InfFile=MSXMLX.inf
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall
ExtractCab=0
UseRollback=1
RebootAfter=0
ValidOS=8
CheckXPakVer=1

[SQLXMLX]
Name=XML Extensions for Microsoft OLE DB Provider for SQL Server
ComponentName=SQLXMLX_MDAC28SP1
Catalog=
Dependencies=WDSETUP28SP1,MDAC_CORE28SP1,MSXML_MDAC28SP1
InstallType=inf
CabFile=SQLXMLXP.cab
InfFile=SQLXMLX.inf
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall.NT
ExtractCab=0
UseRollback=1
RebootAfter=0
ValidOs=23

[SQLXMLX_XPAK]
Name=XML Extensions for Microsoft OLE DB Provider for SQL Server
ComponentName=SQLXMLX_MDAC28SP1
Catalog=SQLXMLXP.CAT
Dependencies=WDSETUP28SP1,MDAC_CORE28SP1,MSXML_MDAC28SP1
InstallType=xpak
CabFile=SQLXMLXP.cab
InfFile=SQLXMLXP.inf
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall
ExtractCab=0
UseRollback=1
RebootAfter=0
ValidOS=8
CheckXPakVer=1


[SQLNET_DOWNLEVEL]
Name=Microsoft SQL Server Network Libraries
ComponentName=SQLNET_MDAC28SP1
Catalog=
Dependencies=
InstallType=inf
CabFile=SQLNET.CAB
InfFile=SQLNETDL.INF
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall.NT
ExtractCab=0
UseRollback=1
RebootAfter=0
ValidOs=7


[SQLNET_MILLENNIUM]
Name=Microsoft SQL Server Network Libraries
ComponentName=SQLNET_MDAC28SP1
Catalog=
Dependencies=
InstallType=inf
CabFile=SQLNET.CAB
InfFile=SQLNETM.INF
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall
ExtractCab=0
UseRollback=1
RebootAfter=0
ValidOs=16

[SQLNET_W2K_MIGRATION]
Name=Microsoft SQL Server Network Libraries
ComponentName=SQLNET_MDAC28SP1
Catalog=SQLNET.CAT
Dependencies=
InstallType=xpak
CabFile=SQLNET.CAB
InfFile=SQLNET.INF
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall
ExtractCab=0
UseRollback=1
RebootAfter=0
ValidOs=31
CheckXPakVer=1


[SQLOLEDB_DOWNLEVEL]
Name=Microsoft SQL Server OLE DB Provider
ComponentName=SQLOLEDB_MDAC28SP1
Catalog=
Dependencies=MDAC_CORE28SP1,SQLXMLX_MDAC28SP1,SQLNET_MDAC28SP1
InstallType=inf
CabFile=SQLOLDB.CAB
InfFile=SQLOL_DL.INF
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall.NT
ExtractCab=0
UseRollback=1
RebootAfter=0
ValidOs=7

[SQLOLEDB_MILLENNIUM]
Name=Microsoft SQL Server OLE DB Provider
ComponentName=SQLOLEDB_MDAC28SP1
Catalog=
Dependencies=MDAC_CORE28SP1,SQLXMLX_MDAC28SP1,SQLNET_MDAC28SP1
InstallType=inf
CabFile=SQLOLDB.CAB
InfFile=SQLOLDBM.INF
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall
ExtractCab=0
UseRollback=1
RebootAfter=0
ValidOs=16

[SQLOLEDB_W2K_MIGRATION]
Name=Microsoft SQL Server OLE DB Provider
ComponentName=SQLOLEDB_MDAC28SP1
Catalog=SQLOLDB.CAT
Dependencies=MDAC_CORE28SP1,SQLXMLX_MDAC28SP1,SQLNET_MDAC28SP1
InstallType=xpak
CabFile=SQLOLDB.CAB
InfFile=SQLOLDB.INF
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall
ExtractCab=0
UseRollback=1
RebootAfter=0
ValidOs=31
CheckXPakVer=1


[SQLODBC_DOWNLEVEL]
Name=Microsoft SQL Server ODBC Driver
ComponentName=SQLODBC_MDAC28SP1
Catalog=
Dependencies=WDSETUP28SP1,SQLNET_MDAC28SP1
InstallType=inf
CabFile=SQLODBC.CAB
InfFile=SQLOD_DL.INF
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall.NT
PostInstallCmd=%11%\odbcconf.exe /S /Lv %25%\dasetup.log /F %11%\sqlclnt.rsp
ExtractCab=0
UseRollback=1
RebootAfter=0
ValidOs=7


[SQLODBC_MILLENNIUM]
Name=Microsoft SQL Server ODBC Driver
ComponentName=SQLODBC_MDAC28SP1
Catalog=
Dependencies=WDSETUP28SP1,SQLNET_MDAC28SP1
InstallType=inf
CabFile=SQLODBC.CAB
InfFile=SQLODBCM.INF
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall
PostInstallCmd=%11%\odbcconf.exe /S /Lv %25%\dasetup.log /F %11%\sqlclnt.rsp
ExtractCab=0
UseRollback=1
RebootAfter=0
ValidOs=16

[SQLODBC_W2K_MIGRATION]
Name=Microsoft SQL Server ODBC Driver
ComponentName=SQLODBC_MDAC28SP1
Catalog=SQLODBC.CAT
Dependencies=WDSETUP28SP1,SQLNET_MDAC28SP1
InstallType=xpak
CabFile=SQLODBC.CAB
InfFile=SQLODBC.INF
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall
PostInstallCmd=%11%\odbcconf.exe /S /Lv %25%\dasetup.log /F %11%\sqlclnt.rsp
ExtractCab=0
UseRollback=1
RebootAfter=0
ValidOs=31
CheckXPakVer=1


[JET_FILES]
Name=Jet Expression Service and String Sorting Libraries
ComponentName=JETES
Catalog=
Dependencies=
InstallType=inf
CabFile=JETFILES.cab
InfFile=JETFILES.inf
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall.NT
ExtractCab=0
UseRollback=1
RebootAfter=0
ValidOs=7

[NEW_MUI_ENGINE]
Name=Microsoft MUI Setup Engine
ComponentName=NEWMUI
Catalog=
Dependencies=
InstallType=inf
CabFile=NEWMUI.CAB
InfFile=NEWMUI.INF
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall
ExtractCab=0
UseRollback=0
RebootAfter=0
ValidOs=8

[REG_MDAC_VERSION]
Name=Microsoft Data Access Components
ComponentName=REG_MDAC_VERSION
Catalog=
Dependencies=MDAC_CORE28SP1,WDSETUP28SP1,MSXML_MDAC28SP1,SQLXMLX_MDAC28SP1,SQLNET_MDAC28SP1,SQLOLEDB_MDAC28SP1,SQLODBC_MDAC28SP1
InstallType=inf
CabFile=
InfFile=noop.inf
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall
PostInstallCmd=%11%\odbcconf.exe /S /Lv %25%\dasetup.log /F %11%\redist.rsp
ExtractCab=0
UseRollback=0
RebootAfter=0
ValidOs=31

[BID_INTERFACE]
Name=Microsoft Data Access Components
ComponentName=BIDINTERFACE
Catalog=
Dependencies=MDAC_CORE28SP1
InstallType=inf
CabFile=
InfFile=bidinter.inf
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall
PostInstallCmd=
ExtractCab=0
UseRollback=0
RebootAfter=0
ValidOs=4

[BID_INTERFACE_XP]
Name=Microsoft Data Access Components
ComponentName=BIDINTERFACE
Catalog=bidintrx.cat
Dependencies=MDAC_CORE28SP1
InstallType=XPAK
CabFile=
InfFile=bidintrx.inf
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall
PostInstallCmd=
ExtractCab=0
UseRollback=0
RebootAfter=0
ValidOs=32
CheckXPakVer=1


[BID_W2K]
Name=Microsoft Data Access Components
ComponentName=BIDINTERFACE
Catalog=bidintrx.cat
Dependencies=MDAC_CORE28SP1
InstallType=XPAK
CabFile=
InfFile=bidintrx.inf
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall
PostInstallCmd=secedit /quiet /configure /db %11%\..\inf\bidintrx.sdb /cfg %11%\..\inf\bidintrx.inf /log %11%\..\inf\bidintrx.log 
ExtractCab=0
UseRollback=0
RebootAfter=0
ValidOs=8
CheckXPakVer=1

[FINISH]
Name=Microsoft Data Access Components
ComponentName=REG_MDAC_VERSION
Catalog=
Dependencies=MDAC_CORE28SP1,WDSETUP28SP1,MSXML_MDAC28SP1,SQLXMLX_MDAC28SP1,SQLNET_MDAC28SP1,SQLOLEDB_MDAC28SP1,SQLODBC_MDAC28SP1
InstallType=inf
CabFile=
InfFile=noop.inf
InstallSection=DefaultInstall
InstallSection.NT=DefaultInstall
PostInstallCmd=
ExtractCab=0
UseRollback=0
RebootAfter=0
ValidOs=4294967295


; ValidOS values
;  these can be OR'd together..
; Win95 = 1
; Win98 = 2
; NT4 = 4
; W2K = 8
; Millennium = 16
; WXP = 32
; W2k3 = 64
; All = 4294967295 (0xFFFFFFFF)
