name: Linux
on:
  push:
    branches: ["main"]
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  Build:
    runs-on: ubuntu-latest
    #if: github.repository_owner == 'myridia'

    steps:
      - name: Dependencies
        run: |
         sudo apt-get update -y      
         sudo apt-get install fuse libfuse2t64 -y 
         
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          ARCH=x86_64 ./appimagetool-x86_64.AppImage  hello.AppDir/
                     


      - name: Release
        if: github.repository_owner == 'myridia'                  
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'Hello-x86_64.AppImage'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true



          


    
   


        


        


 
     
